"use client";

import { useState } from "react";

const publicItems = [
  { name: "Gin Tônica da Casa", description: "Gin, tônica artesanal, limão siciliano e alecrim.", price: "R$ 32", tone: "blue" },
  { name: "Negroni", description: "Gin, vermute rosso, Campari e laranja.", price: "R$ 35", tone: "wine" },
  { name: "Moscow Mule", description: "Vodka, limão, gengibre e espuma da casa.", price: "R$ 34", tone: "green" },
];

const publicStyles = `
.public-menu-shell{min-height:100vh;background:#f8faf8;color:#183344;font-family:Inter,system-ui,sans-serif}.public-top{height:72px;display:flex;align-items:center;justify-content:space-between;padding:0 max(24px,calc((100% - 960px)/2));border-bottom:1px solid #e5ecea;background:#fff}.public-logo{font-weight:800;letter-spacing:-.6px;color:#12334b}.public-top button{background:none;color:#397289;font-size:11px}.public-hero{max-width:960px;margin:auto;padding:72px 24px 62px;background:radial-gradient(circle at 78% 35%,#d4ebe4 0,transparent 31%)}.public-hero h1{font-size:48px;line-height:1.01;letter-spacing:-2px;margin:15px 0}.public-hero h1 em{font-family:Georgia,serif;color:#377e82;font-weight:400}.public-hero p{font-size:13px;color:#7c8e95;max-width:350px;line-height:1.6}.public-content{max-width:960px;margin:auto;padding:0 24px 60px}.public-category{display:flex;align-items:baseline;gap:14px;margin-bottom:16px}.public-category span{font-size:9px;letter-spacing:1.4px;color:#a78b55;font-weight:800}.public-category strong{font-size:15px}.public-items{display:grid;grid-template-columns:repeat(3,1fr);gap:13px}.public-item{background:#fff;border:1px solid #e2ece9;border-radius:12px;overflow:hidden}.public-art{height:145px;display:grid;place-items:center;color:#fff;font-size:38px}.public-art.blue{background:linear-gradient(145deg,#7ebec7,#e1efdb)}.public-art.wine{background:linear-gradient(145deg,#693c51,#d7a09a)}.public-art.green{background:linear-gradient(145deg,#7d9c87,#dae5bd)}.public-item>div:last-child{padding:16px}.public-item-type{font-size:8px;letter-spacing:1px;color:#9aa8a6}.public-item h2{font-size:15px;margin:7px 0}.public-item p{font-size:10px;color:#7d8c91;line-height:1.5;min-height:31px}.public-item strong{font-size:12px;color:#387781}.blurred{filter:blur(4px);pointer-events:none;user-select:none}.age-notice{display:flex;align-items:center;gap:14px;padding:15px;background:#fff9ed;border:1px solid #f1dfb5;border-radius:10px;margin:0 0 15px}.age-notice>span{font-size:24px;color:#b58e48}.age-notice div{flex:1}.age-notice strong{font-size:11px}.age-notice p{font-size:10px;color:#8f8064;margin:4px 0 0}.age-notice button{background:#b68b40;color:#fff;border-radius:6px;padding:9px 11px;font-size:9px;font-weight:700}.whatsapp-button{display:block;margin:25px auto 0;background:#1c9a72;color:#fff;border-radius:7px;padding:12px 17px;font-size:10px;font-weight:700}.public-menu-shell footer{text-align:center;padding:24px;color:#9aa8a6;font-size:9px;border-top:1px solid #e5ecea}.public-menu-shell footer strong{color:#397289}@media(max-width:720px){.public-hero{padding-top:48px;padding-bottom:40px}.public-hero h1{font-size:38px}.public-items{grid-template-columns:1fr}.age-notice{align-items:flex-start;flex-wrap:wrap}.age-notice button{width:100%}}
`;

export default function PublicMenu({ params }: { params: { slug: string } }) {
  const [adult, setAdult] = useState(false);
  const establishment = params.slug.replaceAll("-", " ").replace(/w/g, (letter) => letter.toUpperCase());
  return <main className="public-menu-shell"><style>{publicStyles}</style><header className="public-top"><span className="public-logo">bar flow</span><button>Compartilhar ↗</button></header><section className="public-hero"><span className="eyebrow">CARDÁPIO DIGITAL</span><h1>{establishment || "Casa Caju"}<br /><em>Drinks que contam histórias.</em></h1><p>Uma seleção autoral para noites leves e encontros longos.</p></section><div className="public-content"><div className="public-category"><span>DESTAQUES</span><strong>Uma seleção da casa</strong></div>{!adult && <div className="age-notice"><span>◌</span><div><strong>Conteúdo para maiores de 18 anos</strong><p>Este cardápio pode conter bebidas alcoólicas. Confirme sua maioridade para continuar.</p></div><button onClick={() => setAdult(true)}>Sou maior de 18 anos</button></div>}<div className={adult ? "public-items" : "public-items blurred"}>{publicItems.map((item) => <article className="public-item" key={item.name}><div className={`public-art ${item.tone}`}>◒</div><div><span className="public-item-type">DRINK DA CASA</span><h2>{item.name}</h2><p>{item.description}</p><strong>{item.price}</strong></div></article>)}</div><button className="whatsapp-button">Falar com a Casa Caju pelo WhatsApp <span>→</span></button></div><footer>Powered by <strong>bar flow</strong> · consumo responsável</footer></main>;
}
