"use client";

import { useEffect, useMemo, useState } from "react";
import { fetchPublicMenu, type PublicMenuData } from "../../src/lib/barflow";

const styles = `
.shell{min-height:100vh;background:#f8faf8;color:#183344;font-family:Inter,system-ui,sans-serif}.top{height:72px;display:flex;align-items:center;justify-content:space-between;padding:0 max(24px,calc((100% - 960px)/2));border-bottom:1px solid #e5ecea;background:#fff}.logo{font-weight:800;color:#12334b}.top button{background:none;color:#397289;font-size:11px}.hero{max-width:960px;margin:auto;padding:72px 24px 62px;background:radial-gradient(circle at 78% 35%,#d4ebe4 0,transparent 31%)}.hero h1{font-size:48px;line-height:1.01;letter-spacing:-2px;margin:15px 0}.hero h1 em{font-family:Georgia,serif;color:#377e82;font-weight:400}.hero p{font-size:13px;color:#7c8e95;max-width:350px;line-height:1.6}.content{max-width:960px;margin:auto;padding:0 24px 60px}.category{display:flex;align-items:baseline;gap:14px;margin-bottom:16px}.category span{font-size:9px;letter-spacing:1.4px;color:#a78b55;font-weight:800}.category strong{font-size:15px}.items{display:grid;grid-template-columns:repeat(3,1fr);gap:13px}.item{background:#fff;border:1px solid #e2ece9;border-radius:12px;overflow:hidden}.art{height:145px;display:grid;place-items:center;color:#fff;font-size:38px}.art:nth-child(1){background:linear-gradient(145deg,#7ebec7,#e1efdb)}.item-body{padding:16px}.item-type{font-size:8px;letter-spacing:1px;color:#9aa8a6}.item h2{font-size:15px;margin:7px 0}.item p{font-size:10px;color:#7d8c91;line-height:1.5;min-height:31px}.item strong{font-size:12px;color:#387781}.blurred{filter:blur(4px);pointer-events:none;user-select:none}.age{display:flex;align-items:center;gap:14px;padding:15px;background:#fff9ed;border:1px solid #f1dfb5;border-radius:10px;margin:0 0 15px}.age div{flex:1}.age strong{font-size:11px}.age p{font-size:10px;color:#8f8064;margin:4px 0}.age button{background:#b68b40;color:#fff;border-radius:6px;padding:9px 11px;font-size:9px;font-weight:700}.whatsapp{display:block;width:max-content;margin:25px auto 0;background:#1c9a72;color:#fff;border-radius:7px;padding:12px 17px;font-size:10px;font-weight:700}.shell footer{text-align:center;padding:24px;color:#9aa8a6;font-size:9px;border-top:1px solid #e5ecea}.shell footer strong{color:#397289}@media(max-width:720px){.hero{padding-top:48px;padding-bottom:40px}.hero h1{font-size:38px}.items{grid-template-columns:1fr}.age{align-items:flex-start;flex-wrap:wrap}.age button{width:100%}}
`;

function tone(index: number) { return ["#7ebec7,#e1efdb", "#693c51,#d7a09a", "#7d9c87,#dae5bd", "#b68b40,#f1dfb5"][index % 4]; }

export default function PublicMenu({ params }: { params: { slug: string } }) {
  const [adult, setAdult] = useState(false);
  const [menu, setMenu] = useState<PublicMenuData | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; fetchPublicMenu(params.slug).then((result) => { if (active) { setMenu(result.data); setLoading(false); } }); return () => { active = false; }; }, [params.slug]);
  const establishment = menu?.establishment;
  const phone = establishment?.phone?.replace(/\D/g, "");
  const whatsappUrl = useMemo(() => phone ? `https://wa.me/${phone}` : null, [phone]);
  const share = async () => { if (navigator.share) await navigator.share({ title: establishment?.name ?? "Bar Flow", url: window.location.href }); else await navigator.clipboard?.writeText(window.location.href); };
  return <main className="shell"><style>{styles}</style><header className="top"><span className="logo">bar flow</span><button onClick={share}>Compartilhar →</button></header><section className="hero"><span> CARDÁPIO DIGITAL</span><h1>{establishment?.name ?? params.slug.replaceAll("-", " ")}<br /><em>Drinks que contam histórias.</em></h1><p>{establishment?.public_description ?? "Uma seleção autoral para noites leves e encontros longos."}</p></section><div className="content"><div className="category"><span>DESTAQUES</span><strong>Uma seleção da casa</strong></div>{!adult && <div className="age"><span>◉</span><div><strong>Conteúdo para maiores de 18 anos</strong><p>Este cardápio pode conter bebidas alcoólicas. Confirme sua maioridade para continuar.</p></div><button onClick={() => setAdult(true)}>Sou maior de 18 anos</button></div>}{loading ? <p>Carregando cardápio...</p> : menu && menu.items.length > 0 ? <div className={adult ? "items" : "items blurred"}>{menu.items.map((item, index) => <article className="item" key={item.id}><div className="art" style={{ background: `linear-gradient(145deg,${tone(index)})` }}>◒</div><div className="item-body"><span className="item-type">{item.item_type === "product" ? "PRODUTO" : "DRINK DA CASA"}</span><h2>{item.name}</h2><p>{item.description ?? "Detalhes disponíveis no estabelecimento."}</p><strong>{item.public_price == null ? "Consultar" : new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(item.public_price)}</strong></div></article>)}</div> : <p>Este estabelecimento ainda não publicou itens no cardápio.</p>}{whatsappUrl && <a className="whatsapp" href={whatsappUrl} target="_blank" rel="noreferrer">Falar com {establishment?.name ?? "a casa"} pelo WhatsApp →</a>}</div><footer>Powered by <strong>bar flow</strong> · consumo responsável</footer></main>;
}
